function measModel_16el = ekf_measModel_16el(in1)
%ekf_measModel_16el
%    measModel_16el = ekf_measModel_16el(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    07-Oct-2025 20:09:57

p1 = in1(1,:);
p2 = in1(2,:);
p3 = in1(3,:);
q1 = in1(4,:);
q2 = in1(5,:);
q3 = in1(6,:);
q4 = in1(7,:);
measModel_16el = [p1;p2;p3;q1;q2;q3;q4];
end
